#!/usr/bin/env bash

DOTFILE_HOME=$(cd "$(dirname "$0")" ; pwd -P)

source "$DOTFILE_HOME/zshenv"
source "$DOTFILE_HOME/zprofile"
source "$DOTFILE_HOME/zshrc"
tmux source-file "$DOTFILE_HOME/tmux.conf"
